encoder_op_list_name_dict = {
  "5x2_ryrz_circular_cnot": [
    {"input_idx": [0], "func": "ry", "wires": [0]},
    {"input_idx": [1], "func": "ry", "wires": [1]},
    {"input_idx": [2], "func": "ry", "wires": [2]},
    {"input_idx": [3], "func": "ry", "wires": [3]},
    {"input_idx": [4], "func": "ry", "wires": [4]},
    {"input_idx": [5], "func": "rz", "wires": [0]},
    {"input_idx": [6], "func": "rz", "wires": [1]},
    {"input_idx": [7], "func": "rz", "wires": [2]},
    {"input_idx": [8], "func": "rz", "wires": [3]},
    {"input_idx": [9], "func": "rz", "wires": [4]},
    {"input_idx": None, "func": "cnot", "wires": [0, 1]},
    {"input_idx": None, "func": "cnot", "wires": [1, 2]},
    {"input_idx": None, "func": "cnot", "wires": [2, 3]},
    {"input_idx": None, "func": "cnot", "wires": [3, 4]},
    {"input_idx": None, "func": "cnot", "wires": [4, 0]},
    {"input_idx": [10], "func": "ry", "wires": [0]},
    {"input_idx": [11], "func": "ry", "wires": [1]},
    {"input_idx": [12], "func": "ry", "wires": [2]},
    {"input_idx": [13], "func": "ry", "wires": [3]},
    {"input_idx": [14], "func": "ry", "wires": [4]},
    {"input_idx": [15], "func": "rz", "wires": [0]},
    {"input_idx": [0], "func": "rz", "wires": [1]},
    {"input_idx": [1], "func": "rz", "wires": [2]},
    {"input_idx": [2], "func": "rz", "wires": [3]},
    {"input_idx": [3], "func": "rz", "wires": [4]},
    {"input_idx": None, "func": "cnot", "wires": [0, 1]},
    {"input_idx": None, "func": "cnot", "wires": [1, 2]},
    {"input_idx": None, "func": "cnot", "wires": [2, 3]},
    {"input_idx": None, "func": "cnot", "wires": [3, 4]},
    {"input_idx": None, "func": "cnot", "wires": [4, 0]}
  ]
}
